### ISSUE TITLE
Build Home Page

### ISSUE THREAD

**Issue by gastonche** [BuildForSDG/Team-226-Frontend#1]
1. Display description of services provided
1. Display "why you want to use this site" section
1. Footer
1. Header: Login and sign up Links

**Comment by Cressence** [comment]
![Home](https://user-images.githubusercontent.com/16753456/81614488-07b8ec00-93d8-11ea-9192-1ee31addd0f1.png)

**Comment by wadleo** [comment]
@Cressence can we use a different colour from purple, we could go for green and white. What do you guys think?

**Comment by Cressence** [comment]
![Home](https://user-images.githubusercontent.com/16753456/81716830-beb57600-9471-11ea-85ab-d220de55bad5.png)
 @wadleo What do you think of this?

**Comment by wadleo** [comment]
Not bad @cressence, makes more sense. We maintain these colouring all through.
