### ISSUE TITLE
Signup

### ISSUE THREAD

**Issue by gastonche** [BuildForSDG/Team-226-Frontend#2]
Firstname
Lastname
Email
password
Signup button
Link to privacy policies
Terms and condition checkbox
Link to login

**Comment by Cressence** [comment]
![Signup](https://user-images.githubusercontent.com/16753456/81613824-020ed680-93d7-11ea-84af-74e5459dd9a7.png)

Design draft

**Comment by Cressence** [comment]
![Signup](https://user-images.githubusercontent.com/16753456/81720222-03dba700-9476-11ea-8c8b-194e3b239443.png)
