### ISSUE TITLE
[BUG] User can't login

### ISSUE THREAD

**Issue by Cressence** [BuildForSDG/Team-226-Frontend#29]
An error occurs when a user tries to login with correct credentials this is due to the Authorization header being used when the login request is made.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '/sign-in'
2. Enter 'email and password'
3. Click on 'login' button

<img width="1680" alt="Screen Shot 2020-06-06 at 19 48 46" src="https://user-images.githubusercontent.com/16753456/83954557-288f2880-a842-11ea-9bf5-b93d2e4d0437.png">

**Environment (please complete the following information):**
 - OS: MAC
 - Device: DESKTOP
 - Browser CHROME

**Comment by wadleo** [comment]
@Cressence can you check if the auth endpoints have a similar issue, thanks.

**Comment by Cressence** [comment]
@wadleo  yeah! both signup and sign in have the same issue
