### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by gastonche** [BuildForSDG/Team-226-Frontend#3]
Email
Password
Link to reset password
Login button

When account is not verified, show verify account dialog which
- Contains user email
- Contains send verification button.

**Comment by Cressence** [comment]
![Login](https://user-images.githubusercontent.com/16753456/81614139-806b7880-93d7-11ea-9773-c028c583dcd6.png)

![Login unverified](https://user-images.githubusercontent.com/16753456/81614164-8a8d7700-93d7-11ea-8dbd-b4e689f89d85.png)

**Comment by Cressence** [comment]
![Login unverified](https://user-images.githubusercontent.com/16753456/81720045-c7a84680-9475-11ea-9dae-e33a08e6648d.png)
![Login](https://user-images.githubusercontent.com/16753456/81720110-da228000-9475-11ea-85af-464bddb2c029.png)
