### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by gastonche** [BuildForSDG/Team-226-Frontend#4]
Email
Reset password button
Link to login

**Comment by Cressence** [comment]
![Confirm password](https://user-images.githubusercontent.com/16753456/82218691-2fe2a680-9914-11ea-874e-93a0833bda3f.png)
![Reset Password – 1](https://user-images.githubusercontent.com/16753456/82218709-36711e00-9914-11ea-8e12-5f736da6d1db.png)
![Reset Password](https://user-images.githubusercontent.com/16753456/82218725-3a9d3b80-9914-11ea-9838-a0ede142f0fe.png)
